### ISSUE TITLE
message:// Link opens Mail.app instead of MailMate.app

### ISSUE THREAD

**Issue by cmeinerd** [mailmate/omnifocus.mmbundle#4]
Hi,

I really like the Omnifocus MailMate integration, only that the links always open in Mail.app instead of MailMate.app.

How can I change that? 

I already tried to set MailMate as standard email program, that didn't work?

Thanks for any help,
Christian

**Comment by freron** [comment]
Did you use MailMate to set it as the standard email problem (in the General preferences pane)? This is necessary for the `message:` URLs to be bound to MailMate.

**Comment by cmeinerd** [comment]
hmm, I've already done that, but I just checked and mailmate asked me if I want to set it as default for message:// and now it works 👍
