### ISSUE TITLE
AppleScript error when adding message as task with summary

### ISSUE THREAD

**Issue by naupaka** [mailmate/omnifocus.mmbundle#7]
When trying to use OmniFocus bundle's 'Add with summary...", Mailmate hangs and I get the error below:

```
-1712
System Events got an error: AppleEvent timed out.
```

Seems like this broke just recently, but I couldn't tell you exactly when. Maybe OmniGroup changed something about their OF AppleScript library?

OmniFocus Pro: 2.11.2 (v113.29 r299257)
MailMate: Version 1.9.7 (5429)

**Comment by freron** [comment]
I don't currently have any other reports about this, but you might just be the first one.

Have you tried rebooting?

**Comment by naupaka** [comment]
Everything works smoothly again after restart. Sorry for not trying that first...
