### ISSUE TITLE
Issue with Quick Entry integration on OF 3.1

### ISSUE THREAD

**Issue by naupaka** [mailmate/omnifocus.mmbundle#8]
If only one message is selected in MailMate then the Quick Entry window pops up fine with the correct title and task note, but the task is not subsequently saved into the Inbox after selecting 'Save' in the Quick Entry window. If there are multiple messages selected, they all go into the Quick Entry window, but only those after the first are saved as expected into the Inbox. 

I was able to get around this by adding tasks directly into the Inbox and bypassing Quick Entry altogether. It now works for one or many tasks. 

I am not sure if the bug is related to MailMate or OmniFocus-- there have been lots of changes in both recently, but it does seem to be related to the AppleScript part of the bundle. Since I use this integration constantly, I wanted to get it working again ASAP.

In case anyone else is having trouble and comes across this, I was able to get it working temporarily by editing `~/Library/Application\ Support/MailMate/Managed/Bundles/OmniFocus.mmbundle/Support/bin/create_task.scpt` to include only:

```
on run argv
	
	set wasRunning to application "OmniFocus" is running
	set theFilename to item 1 of argv
	set theName to do shell script "head -n1 " & theFilename
	set theNote to do shell script "tail -n+2 " & theFilename
	
	tell application "OmniFocus"
		try
			tell default document
				make new inbox task with properties {name:theName, note:theNote}
			end tell
			activate
			tell application "System Events"
				key code 125
			end tell
		on error errMsg number eNum
			tell application "OmniFocus"
				activate
				display alert eNum message errMsg
			end tell
		end try
	end tell
end run
```

The `key code 125` bit is not necessary, it's just a down arrow key to select the newly added task.

My system: 
MailMate/5539
MacBookPro11,3/x86_64/8/10.14.0
OmniFocus Pro 3.1 (v120.2.0.319513)

**Comment by naupaka** [comment]
I think this is an OmniFocus bug. I have followed up with them via email.

A minimal reproducible AppleScript example that fails to add the task as expected (and has nothing to do with MailMate):

```
tell application "OmniFocus"
	try
		tell quick entry
			make new inbox task with properties {name:"this", note:"that"}
			open
			set note expanded of tree (count of trees) to true
		end tell
	on error errMsg number eNum
		tell application "OmniFocus"
			activate
			display alert eNum message errMsg
		end tell
	end try
end tell
```

**Comment by tannie** [comment]
Thanks! I came here because I had this exact problem and wondered what caused it.

[This thread on the OmniGroup forums](https://discourse.omnigroup.com/t/quick-entry-using-applescript-not-working/42033/) discusses the same problem. I 'solved' it for now by rolling back to 3.0.1 (found it in my Trash).

**Comment by naupaka** [comment]
Fixed in OF 3.1.2 test version. 

From the release notes:

OmniFocus 3.1.2 Test — October 17, 2018

Crash — Fixed a regression where running a script which populated, then opened, quick entry could result in either data loss or a crash.

Closing this issue.

**Comment by freron** [comment]
@naupaka: Thanks for your efforts on looking into this issue! Sorry for the lack of feedback from me during the week.

**Comment by naupaka** [comment]
@freron no worries! I'm glad it's resolved now
